config/routes.rb
Rails.application.routes.draw do
  
  resources :talks do
    resources :comments, only: [:create, :destroy]
  end

  root "talks#index"

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]

  delete '/log_out', to: 'sessions#destroy', as: 'logout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :talk
  validates :body, presence: true 
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def authenticate_user!
    unless current_user.present?
      redirect_to new_session_path
    end
  end

  def current_user
    return nil if session[:user_id].blank?
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    current_user.present?
  end
  helper_method :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @talk = Talk.find params[:talk_id]
    @comment = Comment.new comment_params
    @comment.talk = @talk
    @comment.save 
    redirect_to talk_path(@talk), notice: "Comment Created Successfully!"
  end

  def destroy
    @talk = Talk.find params[:talk_id]
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to talk_path(@talk), notice: "Comment Deleted Successfully!"
  end


private
  
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  end

  def create
    user = User.where(username: params[:username]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Incorrect username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: 'Logged out'
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  
  def index
    @talks = Talk.order(:id)
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new talk_params
    @talk.save
    redirect_to @talk, notice: "Talk Successfully Saved!"
  end

  def show
    @talk = Talk.find params[:id]
    @comment = Comment.new
  end

  def edit
    @talk = Talk.find params[:id]
  end

  def update
    @talk = Talk.find params[:id]
    @talk.update talk_params
    redirect_to talk_path
  end

  def destroy
    @talk = Talk.find params[:id]
    @talk.destroy
    redirect_to talks_path, notice: "Talk Deleted Successfully!"
  end

  private 

  def talk_params
    params.require(:talk).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:error] = "Unable to create user"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TedTalks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= link_to 'Log out', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'Log in', new_session_path %>
    <%= link_to 'Sign up', new_user_path %>
  <% end %>
  <div class= "container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/talks/_form.html.erb
<div class= "col-md-12">
  <%= form_for @talk do |t| %>
    <div class= "col-md-2">
      <div class="form-group">
        <%= t.label :title %>
        <%= t.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class= "col-md-5">
      <br>
      <div class="form-group">
        <%= t.label :body %>
        <%= t.text_area :body, class: "form-control" %>
      </div>
      <br>
      <%= t.submit class: "btn btn-primary back-but" %>
    </div>
  <% end %>
</div>

app/views/talks/edit.html.erb
<h1>Edit Talk</h1>

<%= render "form" %>

app/views/talks/index.html.erb
<br>
<div class="centered">
<h1>Welcome To Ted Talks</h1>
</div>
<%= link_to "Creat a Talk", new_talk_path, class: "btn btn-sm btn-primary back-but" %>

<% @talks.each do |x| %>
  <div class="well">
  <h3><%= link_to x.title, x %></h3>
  <p><%= x.body %></p>
  </div>
<% end %>

app/views/talks/new.html.erb
<h1>Create A New Talk</h1>

<%= render "form" %>

app/views/talks/show.html.erb
<div class="centered">
  <h3 class="talk-title"><%= @talk.title %></h3>
</div>
<div class="well">
  <ul>
    <li><%= @talk.body%></li>
  </ul>
<br>
</div>
<%= link_to "Back", talks_path, class: "btn btn-sm btn-primary back-but" %>
<%= link_to "Edit", edit_talk_path, class: "btn btn-sm btn-primary back-but" %>
<%= link_to "Delete", talk_path(@talk), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger back-but" %>
<br>
<%# if user_signed_in? && current_user.has_liked?(@talk) %>
  <!-- This should be refactored to a method inside a model -->
  <%# @like = Like.where(question_id: @question.id, user_id: current_user.id).first %>
  <%# @like = current_user.likes.find_by_talk_id(@talk) %>
  <%#= link_to "UnLike", talk_like_path(@talk, @like), class: "btn btn-danger", method: :delete %>
<%# else %>
  <%#= link_to "Like", talk_likes_path(@talk), class: "btn btn-info", method: :post %>
<%# end %>

<div class="comments-form">
  <%= form_for [@talk, @comment] do |c| %>
    <div class="form-group">
        <%= c.label :Comment, class: "label-comment-form" %>
        <%= c.text_area :body, class: "form-control" %>
   <!--  <div class="clearfix"></div>
    <div class= "col-md-5">
      <br>
      <div class="form-group">
        <%#= t.label :body %>
        <%#= t.text_area :body, class: "form-control" %>
      </div> -->
      <br>
      <%= c.submit class: "btn btn-sm btn-primary back-but" %>
    </div>
  <% end %>
</div>
<div>
  <% @talk.comments.each do |x| %>
    <div class="well">
    <p><%= x.body %></p>
    </div>
    <%= link_to "Delete", talk_comment_path(@talk, x), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger back-but" %>
    <%#= link_to "Like", talk_comment_path(@talk, x), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger back-but" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="panel">
    <%= form_for @user do |f| %>
      <%= f.text_field :username, placeholder: 'Username' %>
      <%= f.text_field :password, type: 'password', placeholder: 'Password' %>
      <%= f.text_field :password_confirmation, type: 'password', placeholder: 'Password confirmation' %>
      <%= f.submit %>
    <% end %>
  </div>
</div>